const taxSchemas = require("./taxSchemas");

async function analyzeTaxDocuments(
  documents,
  groq,
  assessment
) {

  if (!documents || documents.length === 0) {
    throw new Error("No tax documents available for analysis");
  }

  if (!assessment) {
    throw new Error("No tax assessment available for analysis");
  }

  console.log(
    `🧠 Analyzing ${documents.length} tax document(s)...`
  );


  /*
   * ============================================
   * EXTRACTED INFORMATION
   * ============================================
   *
   * Only structured extracted information is sent
   * to the AI.
   */

  const extractedInformation =
    documents.map((document) => ({

      fileName:
        document.fileName,

      documentType:
        document.documentType,

      data:
        document.data

    }));


  console.log(
    "🧪 DATA SENT TO TAX ANALYSIS AI:"
  );

  console.log(
    JSON.stringify(
      extractedInformation,
      null,
      2
    )
  );


  /*
   * ============================================
   * DETERMINISTIC ASSESSMENT
   * ============================================
   *
   * This comes from taxAssessmentEngine.js.
   *
   * The AI MUST treat this as authoritative for
   * numerical calculations and consistency checks.
   */

  console.log(
    "🧮 ASSESSMENT SENT TO TAX ANALYSIS AI:"
  );

  console.log(
    JSON.stringify(
      assessment,
      null,
      2
    )
  );


  /*
   * ============================================
   * AI ANALYSIS
   * ============================================
   */

  const response =
    await groq.chat.completions.create({

      model:
        "openai/gpt-oss-120b",

      temperature:
        0,

      response_format: {
        type: "json_object"
      },

      messages: [

        /*
         * ========================================
         * SYSTEM PROMPT
         * ========================================
         */

        {

          role: "system",

          content: `

You are a tax-document analysis assistant.

Your job is to explain and summarize the
structured tax-document information and the
deterministic assessment produced by the
application.

The deterministic assessment was generated by
the application's tax assessment engine.

The assessment engine is AUTHORITATIVE for:

- numerical calculations
- annualized amounts
- gross income totals
- tax withheld totals
- salary calculations
- bank salary comparisons
- duplicate detection
- taxpayer name conflicts
- employer conflicts
- tax-year consistency
- missing structured information

IMPORTANT:

DO NOT override the assessment engine.

DO NOT recalculate financial values differently.

DO NOT invent financial information.

If the assessment engine identifies an
inconsistency, report it clearly.

If the assessment engine identifies a missing
piece of information, report it clearly.

If the assessment engine cannot calculate
something because information is unavailable,
say that it cannot currently be calculated.

The AI's job is to:

1. Explain the financial evidence.
2. Explain the deterministic calculations.
3. Explain inconsistencies.
4. Explain missing information.
5. Provide a clear overall assessment.
6. Distinguish confirmed facts from limitations.

IMPORTANT:

Do not provide legal or professional tax advice.

Do not make legal conclusions.

Do not determine whether the taxpayer is
legally compliant unless the documents contain
sufficient evidence to support that statement.

Do not invent Pakistani tax rates, tax brackets,
deductions, exemptions, penalties, or laws.

Do not assume that missing information is zero.

Do not assume that all uploaded documents belong
to the same taxpayer unless the evidence supports
that conclusion.

The deterministic assessment below is the
authoritative result of the application's
financial calculations.

DETERMINISTIC TAX ASSESSMENT:

${JSON.stringify(
  assessment,
  null,
  2
)}

Return ONLY valid JSON.

Use exactly this structure:

{
  "summary": "",
  "financialOverview": [],
  "taxOverview": [],
  "incomeSources": [],
  "consistencyChecks": [],
  "missingInformation": [],
  "potentialIssues": [],
  "documentSummary": [],
  "overallAssessment": "",
  "confidence": 0
}

FIELD RULES:

summary:

- Give a concise overall summary of the uploaded
  documents and the assessment.
- Mention important confirmed financial facts.
- Mention important inconsistencies when present.
- Do not invent information.

financialOverview:

- List important financial facts.
- Include amounts and frequencies when available.
- Use the assessment values where applicable.

taxOverview:

- Include tax withheld.
- Include taxable income when available.
- Include tax assessed when available.
- Include tax paid when available.
- Include tax due when available.
- Include tax refund when available.
- If something is unavailable, do not treat it as zero.

incomeSources:

- List income sources supported by the documents.
- Identify the source where possible.
- Do not invent income sources.

consistencyChecks:

- Report the consistency checks performed by the
  deterministic assessment engine.
- Clearly identify confirmed consistency.
- Clearly identify inconsistencies.
- If an inconsistency exists, include the actual
  values and difference reported by the engine.
- Do not remove or ignore engine-detected
  inconsistencies.

missingInformation:

- Include important missing information from the
  assessment.
- Do not invent missing values.
- Do not treat missing information as zero.

potentialIssues:

- Include actual inconsistencies or evidence-based
  concerns identified by the assessment.
- Do not convert every missing field into an issue.
- Do not provide legal conclusions.

documentSummary:

- Provide one short summary for every uploaded
  document.
- Include the filename.
- Include the important information found in that
  document.

overallAssessment:

- Give a professional assessment of the available
  evidence.
- Explain whether the documents appear internally
  consistent.
- Explain important limitations.
- Do not provide professional tax advice.

confidence:

- Integer from 0 to 100.
- Reflect confidence in the DOCUMENT ANALYSIS,
  not legal compliance.
- Lower confidence when important information is
  missing or conflicting.

All array items must be simple strings.

`
        },


        /*
         * ========================================
         * USER DATA
         * ========================================
         */

        {

          role: "user",

          content: `

Analyze the following processed tax documents
using the deterministic assessment provided by
the application.

PROCESSED TAX DOCUMENTS:

${JSON.stringify(
  extractedInformation,
  null,
  2
)}


DETERMINISTIC ASSESSMENT:

${JSON.stringify(
  assessment,
  null,
  2
)}

IMPORTANT:

The assessment engine has already performed the
financial calculations and consistency checks.

Use its results as authoritative.

Do not silently ignore any inconsistency
reported by the assessment engine.

`
        }

      ]

    });


  /*
   * ============================================
   * PARSE AI RESPONSE
   * ============================================
   */

  let resultText =
    response.choices[0].message.content;


  resultText =
    resultText
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();


  const result =
    JSON.parse(resultText);


  /*
   * ============================================
   * FINAL LOG
   * ============================================
   */

  console.log(
    "✅ Tax document analysis completed"
  );


  return result;

}


module.exports =
  analyzeTaxDocuments;